name: speech_to_text_windows
description: A stub implementation for speech_to_text_windows that does nothing (workaround for Windows build issues)
version: 1.0.0+beta.8
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SpeechToTextWindows
